class Ar {
  static Map<String, String> keys = {
    'forgotPassword': 'نسيت كلمة المرور؟',
    'dontHaveAccount': 'ليس لديك حساب؟',
    'alreadyHaveAccount': "لديك حساب بالفعل؟",
    'fullName': 'الاسم الكامل',
    'logIn': 'تسجيل الدخول',
    'email': 'البريد الإلكتروني',
    'register': 'إنشاء حساب',
    'password': 'كلمة المرور',
    'yes': 'نعم',
    'no': 'لا',
    'welcomeBack': 'مرحباً بعودتك',
    'welcomeSubtitle':
        'نحن سعداء لرؤيتك مرة أخرى. لاستخدام حسابك، يجب عليك تسجيل الدخول أولاً.',
    'phoneNumberOrEmail': 'رقم الهاتف / البريد الإلكتروني',
    'signUp': 'إنشاء حساب',
    'orSignUpWith': 'أو سجل الدخول باستخدام...',
    'facebook': 'فيسبوك',
    'google': 'جوجل',
    'createAccount': 'إنشاء حساب',
    'phoneNumber': 'رقم الهاتف',
    'emailOptional': 'البريد الإلكتروني (اختياري)',
    'create': 'إنشاء',
    'termsAndConditions': 'الشروط والأحكام',
    'bySigningUp': 'بالتسجيل، أنت توافق على',
    'createAccountSubtitle': 'نحن سعداء لرؤيتك! أنشئ حسابك للبدء.',
    'forgotYourPassword': 'نسيت كلمة المرور؟',
    'forgotPasswordSubtitle':
        'يرجى إدخال رقم الهاتف المحمول الذي تريد إرسال معلومات إعادة تعيين كلمة المرور إليه',
    'verifyOtp': 'التحقق من رمز OTP',
    'otpVerificationSubtitle':
        'يرجى إدخال الرمز المكون من 6 أرقام المرسل إلى رقم هاتفك',
    'verify': 'التحقق',
    'resendOtp': 'إعادة إرسال رمز OTP',
    'resendOtpIn': 'إعادة إرسال رمز OTP خلال',
    'home': 'الرئيسية',
    'downloads': 'التنزيلات',
    'comingSoon': 'قريباً',
    'menu': 'القائمة',
    'homeSubtitle': 'اكتشف واستمتع بمحتواك المفضل',
    'homeContentPlaceholder': 'سيظهر محتوى الصفحة الرئيسية هنا',
    'noDownloads': 'لا توجد تنزيلات',
    'downloadsSubtitle': 'سيظهر المحتوى الذي تم تنزيله هنا',
    'comingSoonSubtitle': 'ميزات ومحتوى جديد في الطريق. ترقبوا!',
    'guest': 'ضيف',
    'profile': 'الملف الشخصي',
    'settings': 'الإعدادات',
    'helpAndSupport': 'المساعدة والدعم',
    'about': 'حول',
    'logout': 'تسجيل الخروج',
    'viewProfile': 'عرض الملف الشخصي',
    'kidsSafe': 'الأمان للأطفال',
    'logoutConfirmation': 'هل تريد تسجيل الخروج؟',
    'subscription': 'الاشتراك',
    'updateProfile': 'تحديث الملف الشخصي',
    'addAudition': 'إضافة تجربة أداء',
    'watchlist': 'قائمة المشاهدة',
    'favoriteList': 'قائمة المفضلة',
    'auditionList': 'قائمة التجارب',
    'languages': 'اللغات',
    'topByLanguages': 'الأفضل حسب اللغة',
    'genres': 'الأجناس',
    'notifications': 'الإشعارات',
    'accountSetting': 'إعدادات الحساب',
    'aboutUs': 'من نحن',
    'contactUs': 'اتصل بنا',
    'help': 'المساعدة',
    'privacy': 'الخصوصية',
    'myProfile': 'ملفي الشخصي',
    'cancelSubscription': 'إلغاء الاشتراك',
    'cancelSubscriptionConfirmation':
        'هل أنت متأكد أنك تريد إلغاء اشتراكك؟ سيبقى اشتراكك نشطًا حتى نهاية فترة الفوترة الحالية.',
    'upgradeYourPlan': 'ترقية خطتك',
    'upgradeSubscription': 'ترقية الاشتراك',
    'upgradeSubscriptionConfirmation':
        'هل أنت متأكد أنك تريد الترقية إلى هذه الخطة؟ سيتم تحصيل الفرق منك على الفور.',
    'currentSubscription': 'الاشتراك الحالي',
    'subscriptionExpiresOn': 'ينتهي في',
    'subscriptionStartedOn': 'بدأ في',
    'noActiveSubscription': 'لا يوجد اشتراك نشط',
    'upgrade': 'ترقية',
    'cancel': 'إلغاء',
    'manageDevice': 'إدارة الجهاز',
    'privacyPolicy': 'سياسة الخصوصية',
    'shareApp': 'مشاركة التطبيق',
    'rateApp': 'تقييم التطبيق',
    'appName': 'BLF Prime',
    'appVersion': 'الإصدار 1.0.0',
    'editProfile': 'تعديل الملف الشخصي',
    'yourName': 'اسمك',
    'yourEmail': 'بريدك الإلكتروني',
    'yourMobile': 'رقم هاتفك',
    'pickFromGallery': 'اختر من المعرض',
    'pickFromCamera': 'التقط من الكاميرا',
    'featureMovies': 'أفلام مميزة',
    'latestReleases': 'أحدث الإصدارات',
    'latestSeries': 'أحدث المسلسلات',
    'series': 'المسلسلات',
    'movies': 'أفلام',
    'allMovies': 'جميع الأفلام',
    'viewAll': 'عرض الكل',
    'play': 'تشغيل',
    'description': 'الوصف',
    'tags': 'العلامات',
    'cast': 'طاقم العمل',
    'trailers': 'العروض الترويجية',
    'allEpisodes': 'جميع الحلقات',
    'moreLikeThis': 'المزيد من هذا القبيل',
    'watchNow': 'شاهد الآن',
    'searchMovies': 'ابحث عن الأفلام...',
    'noResultsFound': 'لم يتم العثور على نتائج',
    'filters': 'المرشحات',
    'clearAll': 'مسح الكل',
    'type': 'النوع',
    'applyFilters': 'تطبيق المرشحات',
    'purchaseSubscription': 'شراء الاشتراك',
    'uploadAudition': 'رفع الاختبار',
    'title': 'العنوان',
    'name': 'الاسم',
    'textHere': 'اكتب هنا',
    'contactNumber': 'رقم الاتصال',
    'socialMediaLink': 'رابط وسائل التواصل الاجتماعي',
    'shortDescription': 'وصف قصير',
    'upload': 'رفع',
    'noWatchlist': 'لا توجد عناصر في قائمة المشاهدة',
    'noFavorites': 'لا توجد مفضلات بعد',
    'deleteAccount': 'حذف الحساب',
    'deleteAccountConfirmation':
        'هل أنت متأكد أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
    'accountDeletedSuccessfully': 'تم حذف حسابك بنجاح',
    'recentSearches': 'عمليات البحث الأخيرة',
    'noSearchHistory': 'لا يوجد سجل بحث',
    'suggestions': 'اقتراحات',
    'noSuggestionsFound': 'لم يتم العثور على اقتراحات',
  };
}
