class En {
  static Map<String, String> keys = {
    'forgotPassword': 'Forgot Password ?',
    'dontHaveAccount': "Don't have an account?",
    'alreadyHaveAccount': "Already have an account?",
    'fullName': 'Full Name',
    'logIn': 'Log in',
    'email': 'Email',
    'register': 'Register',
    'password': 'Password',
    'yes': 'Yes',
    'no': 'No',
    'welcomeBack': 'Welcome Back',
    'welcomeSubtitle':
        'We happy to seen you again. To use your account, you should log in first.',
    'phoneNumberOrEmail': 'Phone Number / Email',
    'signUp': 'Sign up',
    'orSignUpWith': 'or Sign up in with...',
    'facebook': 'Facebook',
    'google': 'Google',
    'createAccount': 'Create Account',
    'phoneNumber': 'Phone Number',
    'emailOptional': 'Email (Optional)',
    'create': 'Create',
    'termsAndConditions': 'Terms & Conditions',
    'bySigningUp': 'By Signin up, You agree to our',
    'createAccountSubtitle':
        'We are happy to see you! Create your account to get started.',
    'forgotYourPassword': 'Forgot your password ?',
    'forgotPasswordSubtitle':
        'Please enter the email Mobile Number you like your password reset information sent to',
    'verifyOtp': 'Verify OTP',
    'otpVerificationSubtitle':
        'Please enter the 6-digit code sent to your phone number',
    'verify': 'Verify',
    'resendOtp': 'Resend OTP',
    'resendOtpIn': 'Resend OTP in',
    'home': 'Home',
    'downloads': 'Downloads',
    'comingSoon': 'Coming Soon',
    'menu': 'Menu',
    'homeSubtitle': 'Discover and enjoy your favorite content',
    'homeContentPlaceholder': 'Your home content will appear here',
    'noDownloads': 'No Downloads',
    'downloadsSubtitle': 'Downloaded content will appear here',
    'comingSoonSubtitle':
        'New features and content are on the way. Stay tuned!',
    'guest': 'Guest',
    'profile': 'Profile',
    'settings': 'Settings',
    'helpAndSupport': 'Help & Support',
    'about': 'About',
    'logout': 'Logout',
    'viewProfile': 'View Profile',
    'kidsSafe': 'Kids Safe',
    'logoutConfirmation': 'Do you want to logout?',
    'subscription': 'Subscription',
    'updateProfile': 'Update Profile',
    'addAudition': 'Add Audition',
    'watchlist': 'Watchlist',
    'favoriteList': 'Favoritelist',
    'auditionList': 'Auditionlist',
    'languages': 'Languages',
    'topByLanguages': 'Top by Languages',
    'genres': 'Genres',
    'notifications': 'Notifications',
    'accountSetting': 'Account Setting',
    'aboutUs': 'About us',
    'contactUs': 'Contact us',
    'help': 'Help',
    'privacy': 'Privacy',
    'myProfile': 'My Profile',
    'cancelSubscription': 'Cancel Subscription',
    'cancelSubscriptionConfirmation':
        'Are you sure you want to cancel your subscription? Your subscription will remain active until the end of the current billing period.',
    'upgradeYourPlan': 'Upgrade Your Plan',
    'upgradeSubscription': 'Upgrade Subscription',
    'upgradeSubscriptionConfirmation':
        'Are you sure you want to upgrade to this plan? You will be charged the difference immediately.',
    'currentSubscription': 'Current Subscription',
    'subscriptionExpiresOn': 'Expires on',
    'subscriptionStartedOn': 'Started on',
    'noActiveSubscription': 'No Active Subscription',
    'upgrade': 'Upgrade',
    'cancel': 'Cancel',
    'manageDevice': 'Manage Device',
    'privacyPolicy': 'Privacy Policy',
    'shareApp': 'Share App',
    'rateApp': 'Rate App',
    'appName': 'BLF Prime',
    'appVersion': 'Version 1.0.0',
    'editProfile': 'Edit Profile',
    'yourName': 'Your Name',
    'yourEmail': 'Your Email',
    'yourMobile': 'Your Mobile',
    'pickFromGallery': 'Pick From Gallery',
    'pickFromCamera': 'Pick From Camera',
    'featureMovies': 'Feature Movies',
    'latestReleases': 'Latest Releases',
    'latestSeries': 'Latest Series',
    'series': 'Series',
    'movies': 'Movies',
    'allMovies': 'All Movies',
    'viewAll': 'View All',
    'play': 'Play',
    'description': 'Description',
    'tags': 'Tags',
    'cast': 'Cast',
    'trailers': 'Trailers',
    'allEpisodes': 'All Episodes',
    'moreLikeThis': 'More Like This',
    'watchNow': 'Watch Now',
    'searchMovies': 'Search movies...',
    'noResultsFound': 'No results found',
    'filters': 'Filters',
    'clearAll': 'Clear All',
    'type': 'Type',
    'applyFilters': 'Apply Filters',
    'purchaseSubscription': 'Purchase Subscription',
    'uploadAudition': 'Upload Audition',
    'title': 'Title',
    'name': 'Name',
    'textHere': 'Text here',
    'contactNumber': 'Contact Number',
    'socialMediaLink': 'Social Media link',
    'shortDescription': 'Short Description',
    'upload': 'Upload',
    'noWatchlist': 'No items in watchlist',
    'noFavorites': 'No favorites yet',
    'deleteAccount': 'Delete Account',
    'deleteAccountConfirmation':
        'Are you sure you want to delete your account? This action cannot be undone.',
    'accountDeletedSuccessfully': 'Your account has been deleted successfully',
    'recentSearches': 'Recent Searches',
    'noSearchHistory': 'No search history',
    'suggestions': 'Suggestions',
    'noSuggestionsFound': 'No suggestions found',
    'buy': "Buy"
  };
}
