class Hi {
  static Map<String, String> keys = {
    'forgotPassword': 'पासवर्ड भूल गए?',
    'dontHaveAccount': 'खाता नहीं है?',
    'alreadyHaveAccount': 'पहले से खाता है?',
    'fullName': 'पूरा नाम',
    'logIn': 'लॉग इन करें',
    'email': 'ईमेल',
    'register': 'पंजीकरण करें',
    'password': 'पासवर्ड',
    'yes': 'हाँ',
    'no': 'नहीं',
    'welcomeBack': 'वापसी पर स्वागत है',
    'welcomeSubtitle':
        'हम आपको फिर से देखकर खुश हैं। अपने खाते का उपयोग करने के लिए, आपको पहले लॉग इन करना होगा।',
    'phoneNumberOrEmail': 'फोन नंबर / ईमेल',
    'signUp': 'साइन अप करें',
    'orSignUpWith': 'या इसके साथ साइन अप करें...',
    'facebook': 'फेसबुक',
    'google': 'गूगल',
    'createAccount': 'खाता बनाएं',
    'phoneNumber': 'फोन नंबर',
    'emailOptional': 'ईमेल (वैकल्पिक)',
    'create': 'बनाएं',
    'termsAndConditions': 'नियम और शर्तें',
    'bySigningUp': 'साइन अप करके, आप हमारी सहमति देते हैं',
    'createAccountSubtitle':
        'हम आपको देखकर खुश हैं! शुरू करने के लिए अपना खाता बनाएं।',
    'forgotYourPassword': 'आपका पासवर्ड भूल गए?',
    'forgotPasswordSubtitle':
        'कृपया ईमेल मोबाइल नंबर दर्ज करें जिस पर आप अपना पासवर्ड रीसेट जानकारी भेजना चाहते हैं',
    'verifyOtp': 'OTP सत्यापित करें',
    'otpVerificationSubtitle':
        'कृपया अपने फोन नंबर पर भेजे गए 6 अंकों के कोड को दर्ज करें',
    'verify': 'सत्यापित करें',
    'resendOtp': 'OTP पुनः भेजें',
    'resendOtpIn': 'OTP पुनः भेजें',
    'home': 'होम',
    'downloads': 'डाउनलोड',
    'comingSoon': 'जल्दी आ रहा है',
    'menu': 'मेनू',
    'homeSubtitle': 'अपनी पसंदीदा सामग्री खोजें और आनंद लें',
    'homeContentPlaceholder': 'आपकी होम सामग्री यहाँ दिखाई देगी',
    'noDownloads': 'कोई डाउनलोड नहीं',
    'downloadsSubtitle': 'डाउनलोड की गई सामग्री यहाँ दिखाई देगी',
    'comingSoonSubtitle': 'नई सुविधाएं और सामग्री रास्ते में है। बने रहें!',
    'guest': 'अतिथि',
    'profile': 'प्रोफ़ाइल',
    'settings': 'सेटिंग्स',
    'helpAndSupport': 'सहायता और समर्थन',
    'about': 'के बारे में',
    'logout': 'लॉगआउट',
    'viewProfile': 'प्रोफ़ाइल देखें',
    'kidsSafe': 'बच्चों के लिए सुरक्षित',
    'logoutConfirmation': 'क्या आप लॉगआउट करना चाहते हैं?',
    'subscription': 'सदस्यता',
    'updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'addAudition': 'ऑडिशन जोड़ें',
    'watchlist': 'वॉचलिस्ट',
    'favoriteList': 'पसंदीदा सूची',
    'auditionList': 'ऑडिशन सूची',
    'languages': 'भाषाएं',
    'topByLanguages': 'भाषाओं द्वारा शीर्ष',
    'genres': 'शैलियां',
    'notifications': 'सूचनाएं',
    'accountSetting': 'खाता सेटिंग',
    'aboutUs': 'हमारे बारे में',
    'contactUs': 'संपर्क करें',
    'help': 'सहायता',
    'privacy': 'गोपनीयता',
    'myProfile': 'मेरी प्रोफ़ाइल',
    'cancelSubscription': 'सदस्यता रद्द करें',
    'cancelSubscriptionConfirmation':
        'क्या आप वाकई अपनी सदस्यता रद्द करना चाहते हैं? आपकी सदस्यता वर्तमान बिलिंग अवधि के अंत तक सक्रिय रहेगी।',
    'upgradeYourPlan': 'अपनी योजना अपग्रेड करें',
    'upgradeSubscription': 'सदस्यता अपग्रेड करें',
    'upgradeSubscriptionConfirmation':
        'क्या आप वाकई इस योजना में अपग्रेड करना चाहते हैं? आपसे तुरंत अंतर शुल्क लिया जाएगा।',
    'currentSubscription': 'वर्तमान सदस्यता',
    'subscriptionExpiresOn': 'समाप्त होता है',
    'subscriptionStartedOn': 'शुरू हुआ',
    'noActiveSubscription': 'कोई सक्रिय सदस्यता नहीं',
    'upgrade': 'अपग्रेड',
    'cancel': 'रद्द करें',
    'manageDevice': 'डिवाइस प्रबंधित करें',
    'privacyPolicy': 'गोपनीयता नीति',
    'shareApp': 'ऐप साझा करें',
    'rateApp': 'ऐप रेट करें',
    'appName': 'BLF Prime',
    'appVersion': 'संस्करण 1.0.0',
    'editProfile': 'प्रोफ़ाइल संपादित करें',
    'yourName': 'आपका नाम',
    'yourEmail': 'आपका ईमेल',
    'yourMobile': 'आपका मोबाइल',
    'pickFromGallery': 'गैलरी से चुनें',
    'pickFromCamera': 'कैमरे से लें',
    'featureMovies': 'विशेष फिल्में',
    'latestReleases': 'नवीनतम रिलीज़',
    'latestSeries': 'नवीनतम सीरीज़',
    'series': 'सीरीज़',
    'movies': 'फिल्में',
    'allMovies': 'सभी फिल्में',
    'viewAll': 'सभी देखें',
    'play': 'चलाएं',
    'description': 'विवरण',
    'tags': 'टैग',
    'cast': 'कलाकार',
    'trailers': 'ट्रेलर',
    'allEpisodes': 'सभी एपिसोड',
    'moreLikeThis': 'इसी तरह के और',
    'watchNow': 'अभी देखें',
    'searchMovies': 'फिल्में खोजें...',
    'noResultsFound': 'कोई परिणाम नहीं मिला',
    'filters': 'फ़िल्टर',
    'clearAll': 'सभी साफ करें',
    'type': 'प्रकार',
    'applyFilters': 'फ़िल्टर लागू करें',
    'purchaseSubscription': 'सदस्यता खरीदें',
    'uploadAudition': 'ऑडिशन अपलोड करें',
    'title': 'शीर्षक',
    'name': 'नाम',
    'textHere': 'यहाँ टेक्स्ट',
    'contactNumber': 'संपर्क नंबर',
    'socialMediaLink': 'सोशल मीडिया लिंक',
    'shortDescription': 'संक्षिप्त विवरण',
    'upload': 'अपलोड',
    'noWatchlist': 'वॉचलिस्ट में कोई आइटम नहीं',
    'noFavorites': 'अभी तक कोई पसंदीदा नहीं',
    'deleteAccount': 'खाता हटाएं',
    'deleteAccountConfirmation':
        'क्या आप वाकई अपना खाता हटाना चाहते हैं? इस क्रिया को पूर्ववत नहीं किया जा सकता।',
    'accountDeletedSuccessfully': 'आपका खाता सफलतापूर्वक हटा दिया गया है',
    'recentSearches': 'हाल की खोजें',
    'noSearchHistory': 'कोई खोज इतिहास नहीं',
    'suggestions': 'सुझाव',
    'noSuggestionsFound': 'कोई सुझाव नहीं मिला',
  };
}
