// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi9NrVzWM8aVW62U7000nTSEnhopuU7mA',
    appId: '1:932007223008:web:26ab1555f07d78e32f3a85',
    messagingSenderId: '932007223008',
    projectId: 'blf-prime-f1d5b',
    authDomain: 'blf-prime-f1d5b.firebaseapp.com',
    storageBucket: 'blf-prime-f1d5b.firebasestorage.app',
    measurementId: 'G-2G0VW0QG2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3pEHQjKWIKBuA_E0ZqLQ4A_RpbH0T2Q',
    appId: '1:932007223008:android:9632ed97b30b70b52f3a85',
    messagingSenderId: '932007223008',
    projectId: 'blf-prime-f1d5b',
    storageBucket: 'blf-prime-f1d5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYJrRlGvJziL5mkEbem1QgtWlxULPy4Ho',
    appId: '1:932007223008:ios:a652e791426e78ed2f3a85',
    messagingSenderId: '932007223008',
    projectId: 'blf-prime-f1d5b',
    storageBucket: 'blf-prime-f1d5b.firebasestorage.app',
    iosBundleId: 'com.ps.blfLive',
  );
}
